
# Gem::Specification for Campfire-cli-0.0.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: campfire-cli
version: !ruby/object:Gem::Version 
  version: 0.0.1
platform: ruby
authors: 
- Petyo Ivanov
autorequire: 
bindir: bin

date: 2008-08-27 00:00:00 +03:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: tinder
  type: :runtime
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Campfire-cli is a simple command line interface to 37signals campfire product.
email: underlog@gmail.com
executables: 
- campfire
extensions: []

extra_rdoc_files: []

files: 
- CHANGELOG
- README
- Rakefile
- bin/campfire
- Manifest
- campfire-cli.gemspec
has_rdoc: true
homepage: http://reborn.underlog.org
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Campfire-cli
- --main
- README
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: campfire-cli
rubygems_version: 1.2.0
specification_version: 2
summary: Campfire-cli is a simple command line interface to 37signals campfire product.
test_files: []
