
# Gem::Specification for Campfire-cli-0.0.1
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{campfire-cli}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Petyo Ivanov"]
  s.date = %q{2008-08-27}
  s.default_executable = %q{campfire}
  s.description = %q{Campfire-cli is a simple command line interface to 37signals campfire product.}
  s.email = %q{underlog@gmail.com}
  s.executables = ["campfire"]
  s.files = ["CHANGELOG", "README", "bin/campfire", "Manifest", "campfire-cli.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://reborn.underlog.org}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Campfire-cli", "--main", "README"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{campfire-cli}
  s.rubygems_version = %q{1.2.0}
  s.summary = %q{Campfire-cli is a simple command line interface to 37signals campfire product.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if current_version >= 3 then
      s.add_runtime_dependency(%q<tinder>, [">= 0"])
    else
      s.add_dependency(%q<tinder>, [">= 0"])
    end
  else
    s.add_dependency(%q<tinder>, [">= 0"])
  end
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'echoe'  
# 
# Echoe.new('campfire-cli', '0.0.1') do |p|
# 
#   p.changelog        = "CHANGELOG.rdoc"
# 
#   p.author           = "Petyo Ivanov"
#   p.email            = "underlog@gmail.com"
# 
#   p.summary = <<-DESC.strip.gsub(/\n\s+/, " ")
#     Campfire-cli is a simple command line interface to 37signals campfire product. 
#   DESC
# 
#   p.url              = "http://reborn.underlog.org"
#   p.rdoc_pattern     = /^(lib|README.rdoc|CHANGELOG.rdoc)/
# 
#   p.dependencies     = ["tinder"]
#   
# end
